### ISSUE TITLE
comfyui桌面版安装后不显示节点，不知道什么问题

### ISSUE THREAD

**Issue by 8251794** [weilin9999/WeiLin-ComfyUI-prompt-all-in-one#24]
comfyui桌面版安装后不显示节点，不知道什么问题

**Comment by weilin9999** [comment]
能看看报错吗？

**Comment by monero778176** [comment]
手動安裝遇到:
 module for custom nodes: No module named 'translator.alibaba_translator'
但檢查確實在下載的 release zip 檔案都具有對應類
不曉得為甚麼server 這邊抓不到

**Comment by weilin9999** [comment]
> 手動安裝遇到: module for custom nodes: No module named 'translator.alibaba_translator' 但檢查確實在下載的 release zip 檔案都具有對應類 不曉得為甚麼server 這邊抓不到

插件第一次安装的时候，打开UI页面会弹出安装依赖的窗口，你要安装那里面的所有依赖才行的，
这个模块是一个翻译模块alibaba的翻译模块

**Comment by monero778176** [comment]
了解這大概是一系列翻譯的模塊
不過這個import的問題似乎是在開啟UI之前所跳出的錯誤
可能也是致使這個插件無法顯示的原因之一( 猜測應是 無正常建立導致沒顯示於 ui node上)
有嘗試過使用 ` pip install translator` 安裝後，再次執行UI仍然出現上述錯誤
目前使用的環境是conda 虛擬環境 python 3.12版，採用
`python -s ComfyUI\main.py`
執行UI程式

**Comment by weilin9999** [comment]
> 了解這大概是一系列翻譯的模塊 不過這個import的問題似乎是在開啟UI之前所跳出的錯誤 可能也是致使這個插件無法顯示的原因之一( 猜測應是 無正常建立導致沒顯示於 ui node上) 有嘗試過使用 ` pip install translator` 安裝後，再次執行UI仍然出現上述錯誤 目前使用的環境是conda 虛擬環境 python 3.12版，採用 `python -s ComfyUI\main.py` 執行UI程式

如果你想要手动安装模块，你应该要使用comfyui的python环境安装，而不是你电脑window的系统环境下的python安装，因为comfyui的python环境是独立的

**Comment by lalxyy** [comment]
遇到了和楼上一样的问题，具体报错如下。在PyPI找了几个包都不是这里指向的 `translator.alibaba_translator`，请问怎么安装这个包，或者把这个包加入 `requirements.txt`？

```
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.6\ComfyUI\nodes.py", line 2110, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\__init__.py", line 412, in <module>
    from .sd_webui_prompt_all_in_one_app.app import app_start
  File "E:\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\sd_webui_prompt_all_in_one_app\app.py", line 12, in <module>
    from .sd_webui_prompt_all_in_one.scripts.on_app_started import on_app_started
  File "E:\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\sd_webui_prompt_all_in_one_app\sd_webui_prompt_all_in_one\scripts\on_app_started.py", line 18, in <module>
    from physton_prompt.translate import translate
  File "E:\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\sd_webui_prompt_all_in_one_app\sd_webui_prompt_all_in_one\scripts\physton_prompt\translate.py", line 12, in <module>
    from translator.alibaba_translator import AlibabaTranslator
ModuleNotFoundError: No module named 'translator.alibaba_translator'
```

**Comment by weilin9999** [comment]
> 遇到了和楼上一样的问题，具体报错如下。在PyPI找了几个包（`translator`, `translators`, `aliyun-python-sdk-alimt`）都不是这里指向的 `translator.alibaba_translator`，请问怎么安装这个包，或者把这个包加入 `requirements.txt`？
> 
> ```
> Traceback (most recent call last):
>   File "E:\ComfyUI-aki-v1.6\ComfyUI\nodes.py", line 2110, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "E:\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\__init__.py", line 412, in <module>
>     from .sd_webui_prompt_all_in_one_app.app import app_start
>   File "E:\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\sd_webui_prompt_all_in_one_app\app.py", line 12, in <module>
>     from .sd_webui_prompt_all_in_one.scripts.on_app_started import on_app_started
>   File "E:\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\sd_webui_prompt_all_in_one_app\sd_webui_prompt_all_in_one\scripts\on_app_started.py", line 18, in <module>
>     from physton_prompt.translate import translate
>   File "E:\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\sd_webui_prompt_all_in_one_app\sd_webui_prompt_all_in_one\scripts\physton_prompt\translate.py", line 12, in <module>
>     from translator.alibaba_translator import AlibabaTranslator
> ModuleNotFoundError: No module named 'translator.alibaba_translator'
> ```

这个问题可能是你comfyui的python环境有问题，这个模块是插件自带的模块，不是pip安装的
