### ISSUE TITLE
'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by zeseren** [weilin9999/WeiLin-ComfyUI-prompt-all-in-one#30]
在自动加载Lora时报错，调用栈如下：
Traceback (most recent call last):
  File "G:\AIdraw\ComfyUI-aki-v1\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\AIdraw\ComfyUI-aki-v1\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\AIdraw\ComfyUI-aki-v1\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\AIdraw\ComfyUI-aki-v1\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "G:\AIdraw\ComfyUI-aki-v1\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\__init__.py", line 269, in load_lora_great
    lora = comfy.utils.load_torch_file(lora_path, safe_load=True)
  File "G:\AIdraw\ComfyUI-aki-v1\comfy\utils.py", line 35, in load_torch_file
    if ckpt.lower().endswith(".safetensors") or ckpt.lower().endswith(".sft"):
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by zeseren** [comment]
明白了，是不支持lora文件名中的下划线“_”导致的问题

**Comment by 2408576095** [comment]
> 明白了，是不支持lora文件名中的下划线“_”导致的问题
请问从哪里看出来的这个问题(我看了半天没看出报错的原因)

**Comment by zeseren** [comment]
我也不知道，看到它是在处理文件名的时候报错，就试了试，发现是下划线的问题

**Comment by 2408576095** [comment]
> 我也不知道，看到它是在处理文件名的时候报错，就试了试，发现是下划线的问题

好的非常感谢

**Comment by weilin9999** [comment]
可能是分割的时候检测到了对应的字符就分割了导致错误，但是旧插件等后面新插件内测完毕会被逐步替代，感谢你对本插件的支持，目前新插件还在内测当中，具体可以进QQ群内了解
