### ISSUE TITLE
请问这是什么问题

### ISSUE THREAD

**Issue by wencxxxxxx** [weilin9999/WeiLin-ComfyUI-prompt-all-in-one#6]
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI-aki-v1.2\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI-aki-v1.2\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\__init__.py", line 412, in <module>
    from .sd_webui_prompt_all_in_one_app.app import app_start
  File "D:\ComfyUI\ComfyUI-aki-v1.2\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\sd_webui_prompt_all_in_one_app\app.py", line 12, in <module>
    from .sd_webui_prompt_all_in_one.scripts.on_app_started import on_app_started
  File "D:\ComfyUI\ComfyUI-aki-v1.2\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\sd_webui_prompt_all_in_one_app\sd_webui_prompt_all_in_one\scripts\on_app_started.py", line 15, in <module>
    from physton_prompt.get_token_counter import get_token_counter
  File "D:\ComfyUI\ComfyUI-aki-v1.2\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\sd_webui_prompt_all_in_one_app\sd_webui_prompt_all_in_one\scripts\physton_prompt\get_token_counter.py", line 10, in <module>
    from modules import sd_hijack
ImportError: cannot import name 'sd_hijack' from 'modules' (unknown location)

Cannot import D:\ComfyUI\ComfyUI-aki-v1.2\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one module for custom nodes: cannot import name 'sd_hijack' from 'modules' (unknown location)

**Comment by weilin9999** [comment]
插件有更新吗？

**Comment by wencxxxxxx** [comment]
![屏幕截图 2024-10-12 152807](https://github.com/user-attachments/assets/d2cd51be-491a-4110-92f9-ad2d3854b457)

**Comment by wencxxxxxx** [comment]
这是最新的吗

**Comment by weilin9999** [comment]
插件是最新的，那你的comfyui有没有更新？，插件是启动的时候报错吗，还是点了什么功能才报错？

**Comment by weilin9999** [comment]
如果你插件是从老版本更新上来的话，我建议你重新安装插件，重新安装之前你可以把插件备份一下。

**Comment by wencxxxxxx** [comment]
comfyui是最新的，我是第一次安装这个插件，插件是启动的时候报错，没法导入插件。

**Comment by wencxxxxxx** [comment]
![屏幕截图 2024-10-12 154233](https://github.com/user-attachments/assets/2c3523c9-639e-42a8-9d67-eea7e090e7da)

**Comment by weilin9999** [comment]
你这个整合包的python版本是多少？

**Comment by weilin9999** [comment]
刚刚更新了一下插件，你更新试试看，如果有问题再反馈

**Comment by wencxxxxxx** [comment]
![屏幕截图 2024-10-12 171243](https://github.com/user-attachments/assets/0b1daff6-3fa2-4afc-ba12-2023bdf13455)
可以了 谢谢
