### ISSUE TITLE
After updating comfyui v0.2.6 it stopped working.

### ISSUE THREAD

**Issue by dakugoddo** [weilin9999/WeiLin-ComfyUI-prompt-all-in-one#8]

**Comment by weilin9999** [comment]
please provide detailed error information

**Comment by dakugoddo** [comment]
WeiLinComfyUIPromptAllInOne 请求安装依赖成功 =======
Traceback (most recent call last):
  File "C:\Stable Diffusion\ComfyUI-Zluda\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\__init__.py", line 412, in <module>
    from .sd_webui_prompt_all_in_one_app.app import app_start
  File "C:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\sd_webui_prompt_all_in_one_app\app.py", line 8, in <module>
    from gradio import Blocks
ImportError: cannot import name 'Blocks' from 'gradio' (C:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\ComfyUI_UltimateSDUpscale\gradio.py)

Cannot import C:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one module for custom nodes: cannot import name 'Blocks' from 'gradio' (C:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\ComfyUI_UltimateSDUpscale\gradio.py)
WeiLinComfyUIPromptAllInOne 请求安装依赖中.......
WeiLinComfyUIPromptAllInOne 请求安装依赖成功 =======
Traceback (most recent call last):
  File "C:\Stable Diffusion\ComfyUI-Zluda\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one-master\__init__.py", line 412, in <module>
    from .sd_webui_prompt_all_in_one_app.app import app_start
  File "C:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one-master\sd_webui_prompt_all_in_one_app\app.py", line 8, in <module>
    from gradio import Blocks
ImportError: cannot import name 'Blocks' from 'gradio' (C:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\ComfyUI_UltimateSDUpscale\gradio.py)

**Comment by dakugoddo** [comment]
I don't understand programming. If you need I can send you something else, just tell me how.

**Comment by weilin9999** [comment]
Okay, understood. The next version will fix it

**Comment by dakugoddo** [comment]
Thank you. Also, sorry for the immodest question, is it possible to translate the Chinese parts of the interface?

**Comment by weilin9999** [comment]
I will try

**Comment by weilin9999** [comment]
hello, since I don’t have enough personal time, the update plan will start in mid-December, thank you for your support

**Comment by weilin9999** [comment]
hello, it seems that your issue is not a plugin problem, but rather a conflict between the plugins you have installed, or it could be a problem with your Python environment.

**Comment by dakugoddo** [comment]
Thank you, I will re-test the plugin. I installed the latest version and disabled all third-party plugins. All-in-one worked. The problem is solved, but what is strange. I could not find the conflicting plugin. Since when I enabled them, the problem did not appear. You can close this case, I think.
